config/routes.rb
Ocr::Application.routes.draw do
  get "classifier/show"
  post "classifier/test"
  get "classifier/try"
  post "classifier/test_image"

  root 'classifier#show'

end

app/models/classifier.rb
require "libsvm"
require "matrix"

class Classifier
  MODEL_FILE = "models/svm.model"
  # Out of the 28x28 attributes, these were selected as the important ones by PCA.
  # See models/reduce_dimensions.log
  SELECTED_ATTRIBUTES = [101,102,128,129,150,151,153,154,155,156,157,158,180,182,183,184,185,189,191,
                         211,212,214,221,232,238,240,242,243,249,262,263,264,265,267,268,270,271,272,
                         273,284,291,292,296,298,299,300,301,318,319,320,323,324,327,328,330,346,347,
                         348,349,350,351,352,354,355,373,374,375,376,377,378,379,380,381,382,383,401,
                         402,403,404,405,406,407,408,409,410,411,414,428,430,431,432,433,434,435,436,
                         437,438,439,442,456,457,458,460,461,462,463,465,466,483,486,487,488,489,490,
                         491,492,493,494,496,498,514,515,516,517,518,524,539,540,541,542,543,544,545,
                         551,567,568,569,570,572,573,578,594,596,597,598,626,627,655,656,657,658,659]

  attr_reader :problem, :parameter, :model, :results

  def initialize(cache_size: 100, eps: 0.001, c: 1)
    @problem = Libsvm::Problem.new
    @parameter = Libsvm::SvmParameter.new
    @parameter.cache_size = cache_size # in megabytes
    @parameter.eps = eps
    @parameter.c = c
    @model = nil
    reset_results!
  end

  def train(examples, labels)
    labels.map! {|str| DataAccessor.word_to_num str}
    Rails.logger.info "Training LibSVM model with #{examples.size} examples"
    Rails.logger.debug "Number of attributes before reducing: #{examples.first.size}"
    examples.map! do |e|
      e = SELECTED_ATTRIBUTES.map {|i| e[i] }
    end
    Rails.logger.debug "Number of attributes after reducing: #{examples.first.size}"
    features = examples.map {|ary| Libsvm::Node.features(ary) }
    @problem.set_examples(labels, features)
    @model = Libsvm::Model.train(@problem, @parameter)
    Rails.logger.info "Done training model"
  end

  def test(examples, expected_labels, max_datapoints=nil)
    check_model_available?
    reset_results!

    if max_datapoints.present? && max_datapoints > 0
      indices = max_datapoints.times.map{ Random.rand(examples.size) }
      examples = indices.map{ |i| examples[i] }
      expected_labels = indices.map{ |i| expected_labels[i] }
    end

    expected_labels.map! {|str| DataAccessor.word_to_num str}
    Rails.logger.info "Running tests on #{examples.size} examples"
    failure_count = 0
    reporting_step_size = examples.size / 20

    examples.each_with_index do |example, i|
      expected = expected_labels[i].to_i
      reduced_example = SELECTED_ATTRIBUTES.map {|i| example[i]}
      found = @model.predict(Libsvm::Node.features(*reduced_example)).to_i

      @results[:confusion_matrix][found, expected] << i
      failure_count += 1 unless found == expected

      if (i+1) % reporting_step_size == 0
        log_accuracy(failure_count, examples.size, i+1)
      end
    end
    log_accuracy(failure_count, examples.size)
    @results[:accuracy] = 100 - failure_count.to_f / examples.size * 100
    @results_ready = true
  end

  def predict(data)
    check_model_available?
    reduced_data = SELECTED_ATTRIBUTES.map {|i| data[i]}
    @model.predict(Libsvm::Node.features(*reduced_data)).to_i
  end

  def load_model
    @model = Libsvm::Model.load(MODEL_FILE)
  end

  def save_model
    check_model_available?
    @model.save(MODEL_FILE)
    Rails.logger.info "Saved model to #{MODEL_FILE}"
  end

  def check_model_available?
    raise "model not trained yet" if @model.nil?
  end

  def reset_results!
    @results_ready = false
    @results = {
      :accuracy => nil,
      # 10 labels to classify. So 10x10 matrix
      :confusion_matrix => Matrix.build(10, 10) { [] }
    }
  end

  def results_ready?
    @results_ready
  end

  def log_accuracy(failure_count, total_count, milepost=nil)
    total = milepost || total_count
    accuracy = 100 - failure_count.to_f / total * 100
    fmt = "%.2f"
    if milepost.present?
      Rails.logger.debug "Accuracy at #{total}/#{total_count}: #{fmt % accuracy}"
    else
      Rails.logger.info "Accuracy: #{fmt % accuracy.to_f}"
    end
  end
end

app/models/data_accessor.rb
require "csv"

class DataAccessor
  IMAGE_DIMENSIONS = {
    height: 28,
    width: 28
  }

  DATA_DIR = "data"
  FILES = {
    mnist_binary: {
      # http://yann.lecun.com/exdb/mnist/
      train: {
        examples: "mnist/train-images-idx3-ubyte",
        labels: "mnist/train-labels-idx1-ubyte"
      },
      test: {
        examples: "mnist/t10k-images-idx3-ubyte",
        labels: "mnist/t10k-labels-idx1-ubyte"
      }
    },
    raw_csv: {
      train: 'training_data.csv',
      test: 'test_data.csv'
    },
  }

  def self.mnist_data(type)
    accepted_types = FILES[:mnist_binary].keys
    unless accepted_types.include? type
      raise ArgumentError, "unknown type of data requestsed: #{type.inspect}. " +
        "Please specify one of #{accepted_types.inspect}"
    end

    labels_file = FILES[:mnist_binary][type][:labels]
    examples_file = FILES[:mnist_binary][type][:examples]
    labels_and_examples_from_mnist_data(labels_file, examples_file)
  end

  def self.labels_and_examples_from_mnist_data(labels_file, examples_file)
    labels = read_binary_data(labels_file, 8)
    examples = group_images(read_binary_data(examples_file, 16))
    [labels, examples]
  end

  def self.labels_and_examples_from(dataset)
    Rails.logger.info "Reading #{dataset}"
    data = CSV.read(File.join(DATA_DIR, dataset)).drop(1)
    labels = data.map {|d| d.pop }
    [labels, data]
  end

  def self.read_binary_data(filename, offset)
    filename = File.join(DATA_DIR, filename)

    # Skip the first offset bytes - mnsit data organization
    IO.binread(filename, nil, offset).bytes.to_a
  end

  def self.group_images(pixels_ary)
    # Single-array of all the pixels: break them into arrays,
    # where each elem represents one image, of size height*width of the image
    pixels_ary.each_slice(IMAGE_DIMENSIONS[:height] * IMAGE_DIMENSIONS[:width]).to_a
  end

  NUM_AND_WORDS = {
    0 => 'zero',
    1 => 'one',
    2 => 'two',
    3 => 'three',
    4 => 'four',
    5 => 'five',
    6 => 'six',
    7 => 'seven',
    8 => 'eight',
    9 => 'nine',
  }

  def self.num_to_word(num)
    NUM_AND_WORDS.fetch num
  end

  def self.word_to_num(str)
    NUM_AND_WORDS.invert.fetch str
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/classifier_controller.rb
class ClassifierController < ApplicationController
  before_filter :load_model, :only => [:show, :test, :test_image]

  def show
    classifier.reset_results!
  end

  def test
    max_datapoints = params[:data_points].to_i
    test_data_file = DataAccessor::FILES[:raw_csv][:test]
    logger.info "Reading tests data from #{test_data_file}"
    labels, examples = DataAccessor.labels_and_examples_from(test_data_file)
    logger.info "Testsing classifier with #{labels.size} data-points"
    classifier.test(examples, labels, max_datapoints)
    render 'show'
  end

  def try
  end

  def test_image
    uploaded_io = params[:image]
    filename = Rails.root.join('public', 'uploads', uploaded_io.original_filename)
    File.open(filename, 'wb') do |file|
      file.write(uploaded_io.read)
    end
    i = Magick::Image.read(filename)[0]
    data = i.export_pixels(0, 0, i.columns, i.rows, "I")
    @found_class = classifier.predict(data).to_i
    render 'try'
  end

  helper_method :classifier
  def classifier
    @@classifier
  end

  def load_model
    @@classifier ||= Classifier.new(cache_size: 1000).tap do |c|
      logger.info "Loading saved model into classifier"
      c.load_model
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/classifier_helper.rb
module ClassifierHelper
end

app/helpers/data_helper.rb
module DataHelper
end

app/views/classifier/show.html.haml
= content_for(:title, "Classifier")

= form_tag(classifier_test_path) do |f|
  .row
    .columns
      %h5.subheader
        A classifier model using libsvm has been loaded from
        %strong= Classifier::MODEL_FILE
        \. It has the following characteristics:

    .columns
      %table
        %thead
          %tr
            %td Kerenel Type
            %td C
            %td eps
            %td Examples Size
        %tbody
          %tr
            %td Linear
            %td= classifier.parameter.c
            %td= classifier.parameter.eps
            %td 60,000

    .columns
      %h6.subheader
        A test dataset of 10,000 examples is available to test the classifier.

      .row
        .columns.small-5
          %label{for: 'data-points'} How many data points should we test with?
          %input{name: 'data_points', id: 'data-points', type: 'text', placeholder: 'all'}

      .row
        .columns
          %input.button.radius{type: "submit", value: 'Start Test'}

- if classifier.results_ready?
  %h2 Results
  %h4
    Accuracy:
    %strong= classifier.results[:accuracy].round(2)
    \%
  %h4 Confusion Matrix
  %table
    %thead
      %tr
        %th
        - 0.upto(9) do |n|
          %th= n
    %tbody
      - 0.upto(classifier.results[:confusion_matrix].row_size - 1) do |n|
        %tr
          %th= n
          - classifier.results[:confusion_matrix].row(n).each do |column|
            %td
              = column.empty? ? '' : column.size

app/views/classifier/try.html.haml
= content_for(:title, "Try the classifier")

= form_tag(classifier_test_image_path, multipart: true) do |f|
  .row
    .columns
      %h5.subheader
        Try the clasifier on your own hand-writing
  .row
    .columns.small-5
      = file_field_tag :image
  .row
    .columns
      %input.button.radius{type: "submit", value: 'Try'}

%h2
  Prediction:
  %strong= @found_class

app/views/layouts/application.html.haml
!!! 5
%html{lang: 'en'}
  %head
    %meta{charset: 'utf-8'}
    %meta{name: 'viewport', content: 'width=device-width, initial-scale=1.0'}
    %title=  content_for?(:title) ? yield(:title) : 'OCR'
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "vendor/modernizr", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    = render partial: 'shared/nav'
    .row
      .columns
        %h1= content_for?(:title) ? yield(:title) : 'OCR'
    .row
      .columns
        = yield
    = javascript_include_tag "application", "data-turbolinks-track" => true

app/views/shared/_nav.html.haml
%div{class: 'fixed'}
  %nav{class: 'top-bar', 'data-topbar'=>''}
    %ul{class:'title-area'}
      %li{class:'name'}
        %h1
          %a{href:'/'}OCR

    %section{class:'top-bar-section'}
      <!-- Right Nav Section -->
      %ul{class:'right'}
        %li{class:'has-dropdown'}
          %a{href:'/'}About
          %ul{class:'dropdown'}
            %li
              %a{href:'https://github.com/arnab/ocr/'}Source Code
            %li
              %a{href:'https://slid.es/arnab_deka/ml-with-ruby/'}Slides
      <!-- Left Nav Section -->
      %ul{class:'left'}
        %li
          %a{href: "#{classifier_show_path}"}Classifier
        %li
          %a{href: "#{classifier_try_path}"}Try